services:
  fetcher-instance-1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: price-instance-1
    volumes:
      - ./config/tokens1.json:/app/config/tokens1.json
    environment:
      - PROXY_URL=${PROXY_URL_1}
      - PROXY_LOGIN=${PROXY_LOGIN_1}
      - PROXY_PASSWORD=${PROXY_PASSWORD_1}
      - TOKENS_PATH=${TOKENS_FILE_PATH_1}
      - KAFKA_SERVER_HOST=${KAFKA_SERVER_HOST_1}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN_1}
